version: '3.8'
services:
  postgres:
    image: postgres:15.0
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
volumes:
  postgres:
